### ISSUE TITLE
More Examples?

### ISSUE THREAD

**Issue by MCJEModder2026** [Antibioticss/tinyhook#2]
would it be possible if an example of how to hook a function at an offset in the main binary, from an included dylib
also, clang is telling me it does not like your void pointer arithmetic

**Comment by Antibioticss** [comment]
You need to get the address of the function you want to hook in the memory, then hook it like this
```c
tiny_hook(your_function_address, your_hook_function, NULL);
```
You can use `_dyld_get_image_vmaddr_slide` to get the start of the image, then add an offset to get the function address.

**Comment by Antibioticss** [comment]
Added a better example: https://github.com/Antibioticss/tinyhook/commit/2a5b17d3daf2daaa59c329177fce84075feae639
