### ISSUE TITLE
Request for Direct Hook Symbol Support

### ISSUE THREAD

**Issue by marlkiller** [Antibioticss/tinyhook#3]
I hope this library can support direct hook symbols
similar to the implementation found in Dobby:[ Dobby Symbol Resolver](https://github.com/jmpews/Dobby/blob/master/builtin-plugin/SymbolResolver/elf/dobby_symbol_resolver.cc).

**Comment by Antibioticss** [comment]
added: https://github.com/Antibioticss/tinyhook/commit/28098b409db038011fe5b1c03f55eba028ec7e6d
