### ISSUE TITLE
[Question] read issue

### ISSUE THREAD

**Issue by MCJEModder2026** [Antibioticss/tinyhook#5]
would this work for functions without a symbol, such as those in roblox.
i am trying to hook the print function to see if it is possible, and it keeps crashing whenever i call print from c++, but not when anything else prints

**Comment by MCJEModder2026** [comment]
ex, some way of me providing a uintptr_t where the function is at (i can add the slide before)
then i provide what i want it to be replaced with and i somehow get the original

**Comment by Antibioticss** [comment]
Can you show me your code?

**Comment by MCJEModder2026** [comment]
would excerpts of my code be fine? i intend to sell my finished product as a competitor to the existing mac roblox cheats (im making mine for arm instead of intel, so performance isnt gonna suck)

**Comment by Antibioticss** [comment]
Yeah, only the part of calling tinyhook is enough.
Or you can create another simple sample code of how you want to use tinyhook, so I can find the problem.

**Comment by MCJEModder2026** [comment]
<details><summary>im sorry, my c++ compiler has self destructed, how can i fix this</summary>
```bash
whatever [main●●] cmake -DCMAKE_OSX_ARCHITECTURES=arm64 .

CMake Warning at /opt/homebrew/Cellar/cmake/3.30.5/share/cmake/Modules/Platform/Darwin-Initialize.cmake:311 (message):
  Ignoring CMAKE_OSX_SYSROOT value:

   /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.5.sdk

  because the directory does not exist.
Call Stack (most recent call first):
  /opt/homebrew/Cellar/cmake/3.30.5/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake:34 (include)
  CMakeLists.txt:3 (project)


-- The CXX compiler identification is AppleClang 16.0.0.16000026
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - failed
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - broken
CMake Error at /opt/homebrew/Cellar/cmake/3.30.5/share/cmake/Modules/CMakeTestCXXCompiler.cmake:73 (message):
  The C++ compiler

    "/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++"

  is not able to compile a simple test program.

  It fails with the following output:

    Change Dir: '/Volumes/Dock/whatever/CMakeFiles/CMakeScratch/TryCompile-W6dj7m'
    
    Run Build Command(s): /opt/homebrew/Cellar/cmake/3.30.5/bin/cmake -E env VERBOSE=1 /usr/bin/make -f Makefile cmTC_797cb/fast
    /Applications/Xcode.app/Contents/Developer/usr/bin/make  -f CMakeFiles/cmTC_797cb.dir/build.make CMakeFiles/cmTC_797cb.dir/build
    Building CXX object CMakeFiles/cmTC_797cb.dir/testCXXCompiler.cxx.o
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -arch arm64 -MD -MT CMakeFiles/cmTC_797cb.dir/testCXXCompiler.cxx.o -MF CMakeFiles/cmTC_797cb.dir/testCXXCompiler.cxx.o.d -o CMakeFiles/cmTC_797cb.dir/testCXXCompiler.cxx.o -c /Volumes/Dock/whatever/CMakeFiles/CMakeScratch/TryCompile-W6dj7m/testCXXCompiler.cxx
    Linking CXX executable cmTC_797cb
    /opt/homebrew/Cellar/cmake/3.30.5/bin/cmake -E cmake_link_script CMakeFiles/cmTC_797cb.dir/link.txt --verbose=1
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -arch arm64 -Wl,-search_paths_first -Wl,-headerpad_max_install_names CMakeFiles/cmTC_797cb.dir/testCXXCompiler.cxx.o -o cmTC_797cb
    ld: library 'c++' not found
    c++: error: linker command failed with exit code 1 (use -v to see invocation)
    make[1]: *** [cmTC_797cb] Error 1
    make: *** [cmTC_797cb/fast] Error 2
    
    

  

  CMake will not be able to correctly generate this project.
Call Stack (most recent call first):
  CMakeLists.txt:3 (project)
```</details>

**Comment by MCJEModder2026** [comment]
i fixed it, after reinstalling xcode, and uninstalling cmake via brew, then installing the official cmake application

**Comment by Antibioticss** [comment]
So, is there any issue with tinyhook?

**Comment by MCJEModder2026** [comment]
yes, i can probably send code tomorrow, but not right now. im having issues with my gaming pc
all of my tech is giving me trouble all at once it seems

**Comment by MCJEModder2026** [comment]
<details><summary>files</summary><p>
<details><summary>offsets.hpp</summary><p>

not my actual offsets.hpp, but should work. i removed everything except print (btw its a live offset, works on current roblox)

```cpp
#include <mach-o/dyld.h>
#include <cstdint>

#define extract_func(addr, sig) reinterpret_cast<sig>(_dyld_get_image_vmaddr_slide(0) + (uintptr_t)addr)
#define num uintptr_t
namespace addresses {
  num f_print = 0x10120db1c;
}
namespace signatures {
  typedef int (*f_print)(int lvl, const char* text);
}
// #define rbx_function(pname, sig, addr) sig*  ## pname = (sig*)addr;
namespace rbxf {
  // rbx_function(print, signatures::f_print, addresses::f_print);
  auto print = extract_func(addresses::f_print,signatures::f_print);
}
```

</p>
</details>
<details><summary>main.cpp</summary><p>

just an example of what i did

```cpp
#include <tinyhook.h>
#include "./offsets.hpp"

int (*orig_print)(int lvl, const char* text);
int my_print(int lvl, const char* text) {
  printf("print hooked, text: %s\n", text);
  return orig_print(lvl,text) ;
}
void install_print_hook() {
  tiny_hook(rbxf::print,my_print,reinterpret_cast<void**>(&orig_print));
  // test
  rbxf::print(0,"is it hooked?"); // crashes
}

// probably some constructor or whatever here that causes it to load from a inserted dylib
```

</p>
</details>
</details>

**Comment by Antibioticss** [comment]
Can you give me a link of current roblox? I don't know which one you're talking about.

**Comment by MCJEModder2026** [comment]
just go on the roblox website and download installer (on arm mac)
that print offset i provided is outdated, here is a better one: 0x1012306b0
(when u compile the code to a dylib u have to use insert_dylib because roblox disabled dylib loading with enviroment varibles)

**Comment by Antibioticss** [comment]
emm, I see. 

I'm not an experienced cpp programmer, but I think it's not the issue of tinyhook.

I tried your code, and got a zero when I printed the value of `rbxf::print` before calling `tiny_hook`.

If I modified the code like this:

```cpp
void install_print_hook() {
  auto print = extract_func(addresses::f_print,signatures::f_print);
  tiny_hook((void*)print,(void*)my_print,reinterpret_cast<void**>(&orig_print));
  // test
  print(0,"is it hooked?"); // crashes
}
```

it worked.

**Comment by MCJEModder2026** [comment]
it printed "print hooked, text: <whatever>"? or did it just compile
i tried what you did and it does not work

**Comment by Antibioticss** [comment]
look

https://dropover.cloud/f61406

full code here:

offsets.hpp

```cpp
#include <mach-o/dyld.h>
#include <cstdint>

#define extract_func(addr, sig) reinterpret_cast<sig>(_dyld_get_image_vmaddr_slide(0) + (uintptr_t)addr)
#define num uintptr_t
namespace addresses {
  num f_print = 0x1012306b0;
}
namespace signatures {
  typedef int (*f_print)(int lvl, const char* text);
}
// #define rbx_function(pname, sig, addr) sig*  ## pname = (sig*)addr;
namespace rbxf {
  // rbx_function(print, signatures::f_print, addresses::f_print);
  auto print = extract_func(addresses::f_print,signatures::f_print);
}
```

main.cpp

```cpp
#include <stdio.h>
#include "tinyhook.h"
#include "offsets.hpp"

int (*orig_print)(int lvl, const char* text);
int my_print(int lvl, const char* text) {
  printf("print hooked, text: %s\n", text);
  return orig_print(lvl,text) ;
}
void install_print_hook() {
  auto print = extract_func(addresses::f_print,signatures::f_print);
  tiny_hook((void*)print,(void*)my_print,reinterpret_cast<void**>(&orig_print));
  // test
  print(0,"is it hooked?"); // crashes
}

// probably some constructor or whatever here that causes it to load from a inserted dylib

__attribute__((constructor(0))) void load() {
    install_print_hook();
}
```

I compiled it withthis command `clang++ main.cpp -dynamiclib -ltinyhook -L. -o libm.dylib -g --std=c++11`

**Comment by MCJEModder2026** [comment]
are you testing roblox wih it inserted? or are you just compiling it. it compiles fine, but crashes on runtime. (compilation was never an issue, except when cmake broke when it updated)

**Comment by MCJEModder2026** [comment]
ohhhhh, i seeeeee. this might be a threading issue

**Comment by MCJEModder2026** [comment]
it is now segfaulting

**Comment by Antibioticss** [comment]
did you see the screenshot in my post above?

well, it could be the offset changed.

I don't think the segfaulting is related to tinyhook, maybe you should check the argument before calling tinyhook.

**Comment by MCJEModder2026** [comment]
i can verify that the offset is correct because it prints correctly before it gets hooked
roblox only updates on wendsdays to i have to find a new offset for tomorrow

**Comment by MCJEModder2026** [comment]
> did you see the screenshot in my post above?
> 
> well, it could be the offset changed.
> 
> I don't think the segfaulting is related to tinyhook, maybe you should check the argument before calling tinyhook.

how are you inserting the dylib? are you using insert_dylib or are you resigning roblox than using enviroment varibles?

**Comment by Antibioticss** [comment]
I used insert_dylib and resigned the main executable

**Comment by MCJEModder2026** [comment]
well then, my mac is brik then

**Comment by MCJEModder2026** [comment]
i disabled and re-enabled sip on my mac, but i kept unrestricted debugging and dtrace
then i restarted my mac
now my code works flawlessly
maybe my mac just needed a restart

**Comment by MCJEModder2026** [comment]
keep this open tho, ima test if it works with sip

**Comment by Antibioticss** [comment]
yes, it works, my Mac is with sip on.

**Comment by MCJEModder2026** [comment]
i figured it out, something is causing crashes. i dont know how to fix it other than trying random things. so far trying random things has worked
