### ISSUE TITLE
sym_solve 似乎匹配不到 “_$” 开头的符号信息

### ISSUE THREAD

**Issue by marlkiller** [Antibioticss/tinyhook#7]
app: CleanShot X
输出了下 sym_solve 函数中获取到的符号列表, _$ 开头的一概没获取到,好像是 swift 的导出符合。 这种符号要特殊处理吗?

```
sym_solve(
                        [MemoryUtils indexForImageWithName:@"Legit"],                 "_$s5Legit0A9CleanShotC11productName03appE07website5email8delegate15updaterDelegate16cloudAPIDelegateACSS_S3SAA0aK0_pAA0a7UpdaterK0_pAA0a5CloudM0_ptcfc"
     );
```

<img width="1268" alt="1" src="https://github.com/user-attachments/assets/36eaf83b-6590-49da-9c20-c9184138bfdc">
<img width="1432" alt="2" src="https://github.com/user-attachments/assets/4c96d643-0a55-4442-bf25-4b2a56b93fa4">

<img width="1275" alt="image" src="https://github.com/user-attachments/assets/aec773ef-7d8c-44bb-aecd-6fc803b57a4b">

**Comment by Antibioticss** [comment]
这个符号不是正常符号表里的，而是动态库导出函数里的，我会加一个新的函数来处理的

**Comment by Antibioticss** [comment]
在这里支持了 https://github.com/Antibioticss/tinyhook/commit/525dfdb897a86b90e5388a33285c382f6c19ea21
