### ISSUE TITLE
tiny_hook报错 write_mem: (os/kern) invalid address

### ISSUE THREAD

**Issue by nmweizi** [Antibioticss/tinyhook#8]
使用方法
```
  void *symbol_address = symexp_solve(0, "__ZNK9PublicKey6verifyERK10QByteArrayS2_22MessageDigestAlgorithm");
  NSLogger(@"[EVP_DigestVerifyFinal] address: %p",symbol_address);
  tiny_hook(symbol_address ,ret1, NULL);
```

输出：
> address: 0x284bef0
write_mem: (os/kern) invalid address

**Comment by nmweizi** [comment]
用symtbl_solve可以替换成功，不过程序异常退出了。

**Comment by nmweizi** [comment]
能说说symtbl_solve、symexp_solve这个函数的区别吗？

**Comment by Antibioticss** [comment]
`symtbl_solve`是获取符号表里的符号信息，一般是开发者忘记去除的一些函数符号。具体来说，是macho文件位于`SYMTAB`部分的符号
`symexp_solve `是获取导出表里的符号信息，一般是对于动态库中的导出符号，比如Frameworks里的，dylib里的。位于macho文件的`LC_DYLD_INFO_ONLY`段

这两个函数还没有被发布出来，在0.4版本发布之前，我会更新文档的

**Comment by nmweizi** [comment]
感谢

**Comment by marlkiller** [comment]
> `symtbl_solve`是获取符号表里的符号信息，一般是开发者忘记去除的一些函数符号。具体来说，是macho文件位于`SYMTAB`部分的符号 `symexp_solve `是获取导出表里的符号信息，一般是对于动态库中的导出符号，比如Frameworks里的，dylib里的。位于macho文件的`LC_DYLD_INFO_ONLY`段
> 
> 这两个函数还没有被发布出来，在0.4版本发布之前，我会更新文档的

作为一名业余的 c/c++ 开发 , 我理解: 
symtbl_solve: debug 模式下有符号的话 方便调试追踪,可以用 -G 保留 符号信息,  一般 release 下是不需要符号信息的;
symexp_solve: 这个是动态库的接口, 主程序如果调用的话, 这个符号是没办法移除的;


对吗?
